---   # parameter configure
lgMmin:
  free: true
  default: 14
  prior: [10, 17]
sig_lgM:
  free: true
  default: 0.5
  prior: [1e-3, 1]
Amp:
  free: false
  default: 1
  prior: [0, 1]

lgM0:
  free: true
  default: 12
  prior: [11, 16]
lgM1p:
  free: true
  default: 12
  prior: [10.5, 16]
alpha:
  free: true
  default: 1
  prior: [0, 5]

---   # general configure
Nwalkers: 40          # walkers you use
Nstep: 8000           # steps to go
Nburnin: 1000          # burnin
Npro: 40              # process to use

auto_range: [0, 22]   # apply a cut.
cross_range: [0, 0]   # no cross correlation used.
backend_file: result/backend_step_pow_auto.bin # backend file
numpy_file: result/np_step_pow_auto
wp_table_path: ../wp_table_small
signal_path: ../signal_small
module_path: ./HOD/calc_wp_step_power.py